version: '3.7'

services:
  db_postgres:
    image: postgres:10
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  django:
    build: ./src
    command: gunicorn tasks_api.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db_postgres
    env_file: .env
    volumes:
      - ./src:/src
    expose:
      - 8000

    environment:
      - DJANGO_SETTINGS_MODULE=tasks_api.settings.prod

  nginx:
    image: nginx:alpine
    volumes:
      - ./src/static:/static
      - ./src/media:/media
      - ./config/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"

    depends_on:
      - django