version: '3.7'

services:
  db_postgres:
    image: postgres:10
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres:/var/lib/postgresql/data

  django:
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db_postgres
    env_file: .env
    volumes:
      - ./src:/src
    environment:
      - DJANGO_SETTINGS_MODULE=tasks_api.settings.dev
    ports:
      - '8000:8000'